### ISSUE TITLE
Request for Photos

### ISSUE THREAD

**Issue by SCKelemen** [wearehx/wearehx.github.io#6]
I need photos of hackathons and hackers, code, and anything else. Mid to large in size. Any format. 
Can anyone help with this?

**Comment by sdaitzman** [comment]
http://librestock.com/search/?query=coding is not a half-bad place to start :smile:

**Comment by SCKelemen** [comment]
@sdaitzman Thanks, I'll look into using some of those. However, I was looking to find some pictures of real Hackathons and real Hackers\* at said hackathons. looking for contributions from our community.

**Comment by RitwikGupta** [comment]
As a joke: http://hackathoncasualties.tumblr.com/

**Comment by SCKelemen** [comment]
@RitwikGupta I laughed.
